Example of how to load and plot data from excel file

In [28]:
#Loading libraries we will use in this notebook
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [29]:
#The first column (col 0) does not contain anything useful
#Since we already know this we can skip this and just use columns 1-3
data = pd.read_csv('5 svar til aflevering.csv')

In [30]:
#We can print the first five lines in data
data.head(5)

  Id;;;;;Hvor gammel er du?;Hvor høj er du?;Hvilken MobileOS har du?
0                                   1;;;;;21;164;IOS
1                                   2;;;;;21;178;IOS
2                                   3;;;;;21;164;IOS
3                                   4;;;;;21;183;IOS
4                                   5;;;;;24;197;iOS

In [31]:
len(data)

5

In [32]:
#The good thing about dataFrame is the quick description of data 
data.describe()

       Id;;;;;Hvor gammel er du?;Hvor høj er du?;Hvilken MobileOS har du?
count                                                   5
unique                                                  5
top                                      1;;;;;21;164;IOS
freq                                                    1

In [ ]:
Jeg lavede et spørgeskema og sendte det til nogle fra klassen. i spørgsmkemaet har jeg spurgt ind til de